// create web server
// npm install express
// npm install body-parser
// npm install mongoose
// npm install cors
// npm install nodemon
// npm install bcrypt
// npm install jsonwebtoken
// npm install cookie-parser
// npm install dotenv
// npm install uuid
// npm install express-validator
// npm install express-jwt
// npm install express-jwt-authz
// npm install jwks-rsa
// npm install morgan
// npm install multer
// npm install helmet
// npm install compression
// npm install csurf
// npm install express-session
// npm install connect-mongodb-session
// npm install connect-flash
// npm install express-handlebars
// npm install express-validator
// npm install express-validator-handlebars
// npm install passport
// npm install passport-local
// npm install passport-local-mongoose
// npm install passport-google-oauth20
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-github
// npm install express-rate-limit
// npm install express-mongo-sanitize
// npm install sanitize-html
// npm in